[2024-07-12T11:26:36.773+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_data_processing_pipeline.process_data scheduled__2024-07-11T01:00:00+00:00 [queued]>
[2024-07-12T11:26:36.776+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_data_processing_pipeline.process_data scheduled__2024-07-11T01:00:00+00:00 [queued]>
[2024-07-12T11:26:36.776+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-07-12T11:26:36.781+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_data> on 2024-07-11 01:00:00+00:00
[2024-07-12T11:26:36.783+0000] {standard_task_runner.py:57} INFO - Started process 1135 to run task
[2024-07-12T11:26:36.785+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_data_processing_pipeline', 'process_data', 'scheduled__2024-07-11T01:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark-jobs_.py', '--cfg-path', '/tmp/tmpj93fa8fr']
[2024-07-12T11:26:36.787+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask process_data
[2024-07-12T11:26:36.811+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_data_processing_pipeline.process_data scheduled__2024-07-11T01:00:00+00:00 [running]> on host c553c98b8e80
[2024-07-12T11:26:36.843+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T01:00:00+00:00'
[2024-07-12T11:26:36.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-12T11:26:36.844+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /opt/***/scripts/run_spark_job.sh ']
[2024-07-12T11:26:36.848+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T11:26:36.850+0000] {subprocess.py:93} INFO - bash: /opt/***/scripts/run_spark_job.sh: No such file or directory
[2024-07-12T11:26:36.850+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-12T11:26:36.856+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-12T11:26:36.857+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spark_data_processing_pipeline, task_id=process_data, execution_date=20240711T010000, start_date=20240712T112636, end_date=20240712T112636
[2024-07-12T11:26:36.862+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task process_data (Bash command failed. The command returned a non-zero exit code 127.; 1135)
[2024-07-12T11:26:36.882+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T11:26:36.890+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
